# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

volumeBalls3D <- function(X, rad) {
    .Call('_ashapesampler_volumeBalls3D', PACKAGE = 'ashapesampler', X, rad)
}

